### ISSUE TITLE
Bei HTML Modals kommt es zu einem Typen-Problem

### ISSUE THREAD

**Issue by fschmid-dev** [sowieso-web/contao-modal-bundle#5]
In der `src/Modal/Builder.php` wird in der Funktion isModalPage() das PageModal und die Ziel-URL erwartet:
https://github.com/sowieso-web/contao-modal-bundle/blob/9348d2fab8c46c800d7a0d2fdcbd16a40af534eb/src/Modal/Builder.php#L195

Wenn aber als Inhalt für das Modal "HTML" ausgewählt wird, anstatt Text + Bild oder nur Bild, gibt es beim FrontendModul keine Einstellungsmöglichkeiten für eine Weiterleitungs-URL.
Es wird dann `null` als zweiter Parameter übergeben und es kommt zu einem TypeError.

Entweder sollte der Parameter nullable sein oder das Eingabefeld für die Weiterleitungs- bzw. Ziel-URL auch beim Typ "HTML" hinzugefügt werden.
Je nachdem, was hier der gewünschte Weg ist :)

**Comment by Xirdion** [comment]
Thanks for the tip.
With the new version 1.0.4 the error is now fixed.
